### ISSUE TITLE
Standalone Version

### ISSUE THREAD

**Issue by atagulalan** [CakeCrusher/mimicbot#1]
Hello,

This is an awesome work! I was wondering if is there any way we skip discord integration and get results by calling the script on cli?

Thank you,
Ata G

**Comment by CakeCrusher** [comment]
Do you still want to train the model on another user so that it can imitate that user? Or do you just want to interreact with the default chat model?

**Comment by atagulalan** [comment]
I guess training could be done with provided text file beforehand.

**Comment by CakeCrusher** [comment]
Interesting, so the feature would work like this:
1. you provide a data file (chat logs)
2. run forge but opting out of all the discord stuff
3. at the end instead of activating the discord bot you can talk to the model directly by inputting into the cli.

How does that sound?

**Comment by atagulalan** [comment]
That sounds awesome.

**Comment by CakeCrusher** [comment]
@atagulalan you can try it out at the following branch https://github.com/CakeCrusher/mimicbot/tree/discord-independent-mimicbot

The forge is ready. Just run `python -m mimicbot forge` and the CLI will run you through it.

Let me know what you think.

**Comment by atagulalan** [comment]
Thank you, trying it now.

First, I tried to run `python -m mimicbot forge` and it gave me this error:
```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\__main__.py", line 1, in <module>
    from mimicbot import cli, __app_name__
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\cli.py", line 428, in <module>
    utils.session_path(utils.callback_config()),
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\utils.py", line 78, in callback_config
    with open(str(config_path), "w") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\x\\AppData\\Roaming\\mimicbot\\config.ini'
```

I thought to myself, "oh, it couldn't create the config file because we didn't create the folder shuld contain it."; so I created the folder myself and got this error insted:

```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\__main__.py", line 1, in <module>
    from mimicbot import cli, __app_name__
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\cli.py", line 428, in <module>
    utils.session_path(utils.callback_config()),
  File "C:\Users\x\Documents\GitHub\mimicbot\mimicbot\utils.py", line 93, in session_path
    GUILD = config.get("discord", "guild")
  File "C:\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'discord'
```

Should I create a prefilled config file contains those values, or is forge supposed to do that?

Thank you!

**Comment by CakeCrusher** [comment]
Thank you so much for pointing that out that was a fundamental problem that I should have dealt with ago. It is fixed now 9846c0093cec958a211c8d3f71c8e371a4b1cf76

**Comment by atagulalan** [comment]
Thank you, I successfully got to the Step 2 now.
Is it really necessary to author column be integer? I receive error on `data_preprocessing.py line 58` because of my csv data, which author column contains usernames. 

Edit: Also, how about ignoring whole "enter name for member with id" sequence if csv file contains an additional column for names? For example, my file has username and message fields, but not id field. maybe id field could be generated from usernames and we could use usernames as "name of member with id".

**Comment by CakeCrusher** [comment]
You are absolutely right about the `int` issue that is fixed as for the naming I will get to that soon.

**Comment by CakeCrusher** [comment]
Naming of members could always be the same as id. Now (2c6fb4711c45c992c3abea82b82b69dbe85b0312) the name is the id by default.
That among with other strict inputs are things I will need to fix at some point.
